################ Languages ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[zh]
languageName = "中文"
languageCode = "zh-CN"
contentDir = "content/chinese/"
weight = 2
title = "SAS 打击乐教研室"